spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: root123
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
    